name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install --save-dev vite @vitejs/plugin-react typescript @types/node
          npm install -g vite

      - name: Debug Environment
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Installed packages:"
          npm list --depth=0
          echo "PATH:"
          echo $PATH

      - name: Build
        env:
          NODE_ENV: production
        run: |
          # Build the app with base path
          echo "Building application with base path /sLixTOOLS/..."
          npx vite build --base=/sLixTOOLS/
          
          # Show build output
          echo "Build output:"
          ls -la dist/
          
          # Copy public files
          echo "Copying public files..."
          cp -r public/* dist/ 2>/dev/null || :
          
          # Create 404.html for SPA routing
          echo "Creating 404.html for SPA routing..."
          cp dist/index.html dist/404.html
          
          # Show the contents of index.html
          echo "Contents of index.html:"
          cat dist/index.html
          
          # Show final dist contents
          echo "Final dist contents:"
          find dist -type f | sort

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
          clean-exclude: |
            .git
            .github
            .gitignore
            CNAME
