name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install --save-dev @vitejs/plugin-react typescript @types/node

      - name: Build
        run: |
          # Set environment to production
          echo "NODE_ENV=production" >> $GITHUB_ENV
          
          # Install dependencies
          npm install
          
          # Build the app
          echo "Building application..."
          npm run build
          
          # Show build output
          echo "Build output:"
          ls -la dist/
          
          # Copy public files
          echo "Copying public files..."
          cp -r public/* dist/ 2>/dev/null || :
          
          # Ensure the base path is correctly set in index.html
          echo "Updating index.html for production..."
          sed -i 's|/sLixTOOLS/src/|/sLixTOOLS/src/|g' dist/index.html
          
          # Create _redirects file for SPA routing
          echo "/* /sLixTOOLS/index.html 200" > dist/_redirects
          
          # Show final dist contents
          echo "Final dist contents:"
          find dist -type f | sort

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          target-folder: .  # Deploy to root of gh-pages branch
          clean: true
          clean-exclude: |
            .git
            .github
            .gitignore
            CNAME
            **/*
