name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: |
          # Set NODE_ENV to production
          export NODE_ENV=production
          # Install Vite and other build dependencies
          npm install --save-dev vite @vitejs/plugin-react
          # Build the app
          npm run build
          # Create necessary directories
          mkdir -p dist/assets
          # Copy public files
          cp -r public/* dist/ 2>/dev/null || :
          # Ensure the base path is correctly set in index.html
          sed -i 's|/src/main.tsx|/sLixTOOLS/src/main.tsx|g' dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/*'  # Include all files including _redirects and 404.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          target-folder: sLixTOOLS
