name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install --save-dev @vitejs/plugin-react typescript @types/node

      - name: Build
        run: |
          npm install
          npm run build
          
          # Copy public files
          cp -r public/* dist/ 2>/dev/null || :
          
          # Ensure index.html has correct base path
          sed -i 's|/src/|/sLixTOOLS/src/|g' dist/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          target-folder: sLixTOOLS
          clean: true
          clean-exclude: |
            .git
            .github
            .gitignore
            CNAME
